#!/usr/bin/env python3
"""make_sheet.py — beat_sheet.json for "Claude making a film about Muse".

LECTURE, channel claude-liam (Liam, in for Bear · Kokoro am_onyx · @NikBearBrown).
Bear and Claude's opinion on Meta Muse (doc pasted 2026-10-03): what it does,
what it costs, the business model, twelve security concerns, and how Bear
resolved them. Liam narrates their analysis; contested and third-party claims
stay attributed in voice and on screen. See FACTCHECK.md for the attribution map.
"""
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SLUG = "claude-liam-lecture-claude-making-a-film-about-muse"
TITLE = "Claude making a film about Muse"


def beat(bid, act, narration, cls, image, show, claim=None):
    return {
        "beat_id": bid, "act": act, "lane": "manim", "proof_gate": "SHOW",
        "narration_text": narration,
        "estimated_duration_s": round(len(narration.split()) / 2.5, 1),
        "voice": "am_onyx", "engine": "kokoro",
        "shot": {
            "type": "GRAPHIC", "source": "own",
            "visual_intent": image, "show": show,
            "manim": {"class": cls},
            "motion_claim": claim or image,
        },
        "qc": {
            "sparse_by_design": True,
            "sparse_reason": "lecture style: one drawn scene on a cream stage per beat, minimal labels, voice carries the explanation.",
        },
    }


def remotion(bid, act, narration, pattern, props, show, gate="SHOW", **extra):
    b = {
        "beat_id": bid, "act": act, "lane": "bookend", "proof_gate": gate,
        "narration_text": narration,
        "estimated_duration_s": round(len(narration.split()) / 2.5, 1),
        "voice": "am_onyx", "engine": "kokoro",
        "shot": {"type": "REMOTION", "source": "own", "show": show,
                 "remotion": {"pattern": pattern, "props": props}},
    }
    b.update(extra)
    return b


B = [
    # ── ACT I — what it is ────────────────────────────────────────────────
    beat("B01", "what it is",
         "Bear and Claude start with Meta's pitch: 'personal superintelligence,' 'AI That Hustles for You.' Unlike a chatbot, it acts — you set a goal; it plans, works the steps, and checks in before anything consequential.",
         "M01_ActsNotChats",
         "A static speech bubble labeled 'chatbot'; beside it a goal mark, a plan mark, and step marks that build into a flow.",
         [{"at": 0.1, "event": "chatbot bubble, static"},
          {"at": 0.4, "event": "goal → plan → steps builds"}],
         claim="The building flow IS the difference between chatting and acting."),
    beat("B02", "what it is",
         "Meta says: launched in the US September 8th, 2026, on Muse Spark, two and a half million downloads in two weeks. In Nik's experience, the model is noticeably less capable than GPT-6 Astra, Claude Fable, or Claude Opus.",
         "M02_LaunchNumbers",
         "A timeline tick lands on September 8, 2026; a counter climbs to 2.5M; a small label marks the capability take as Nik's.",
         [{"at": 0.15, "event": "tick lands on the date"},
          {"at": 0.45, "event": "counter climbs to 2.5M"},
          {"at": 0.75, "event": "Nik's take labeled"}],
         claim="The climbing counter is the adoption story; the label keeps the take attributed."),
    # ── ACT II — what it does ─────────────────────────────────────────────
    beat("B03", "what it does",
         "Underneath, their read of the machinery: every user gets a persistent Linux computer in Meta's cloud — browser, filesystem, terminal. Same architecture as Claude Cowork and OpenAI Codex; they differ in audience and default permissions.",
         "M03_VMStack",
         "Three blocks — model, sandboxed computer, connectors — drop in and stack into one machine.",
         [{"at": 0.1, "event": "three blocks"},
          {"at": 0.4, "event": "blocks stack"},
          {"at": 0.7, "event": "stack pulses as one machine"}],
         claim="The stacking blocks are the architecture."),
    beat("B04", "what it does",
         "For consumers it's errands: travel, restaurants, appointments, shopping, forms, negotiating, subscriptions, tickets — Ticketmaster was a launch partner. Their point: its strength is endurance, not intelligence. It keeps going; it isn't especially clever.",
         "M04_Endurance",
         "A checklist ticks through task after task while a clock spins — relentless, not clever.",
         [{"at": 0.1, "event": "checklist starts ticking"},
          {"at": 0.35, "event": "clock spins"},
          {"at": 0.7, "event": "ticks accelerate"}],
         claim="Speed plus repetition is the claim; only motion shows it."),
    beat("B05", "what it does",
         "You reach it on web, iPhone, Android, WhatsApp — glasses announced. Connectors skew commerce: Shopify, OpenTable, Ticketmaster, Instacart, Expedia, Stripe. CNBC reported Amazon blocked Muse over its terms. Custom connectors need no Meta review.",
         "M05_Connectors",
         "Surface marks on top; connector pills below; links draw between them — one pill, marked 'Amazon', is crossed out.",
         [{"at": 0.1, "event": "surfaces and pills"},
          {"at": 0.4, "event": "links draw"},
          {"at": 0.75, "event": "Amazon pill crossed out"}],
         claim="The drawn web is the connector story; the crossed pill is the block."),
    beat("B06", "what it does",
         "For small business — September 29th — it drafts posts and campaigns, reads QuickBooks, works Klaviyo and Shopify. Meta says nothing publishes, sends, or spends without approval. Developers get the Muse Spark API — not the consumer agent.",
         "M06_BusinessDev",
         "A split screen: a storefront with an ad draft on the left, a terminal with code on the right.",
         [{"at": 0.15, "event": "storefront side"},
          {"at": 0.5, "event": "terminal side"}],
         claim="The split screen holds both audiences at once."),
    # ── ACT III — money ───────────────────────────────────────────────────
    beat("B07", "money",
         "Three tiers, per the document. Free: zero dollars, a hundred million Muse tokens a week. Power: twenty a month, five hundred million. Maximum: a hundred a month, three billion. Same features — you pay for volume. Card required even for free.",
         "M07_Tiers",
         "A three-column table builds cell by cell: Free $0 / 100M, Power $20 / 500M, Maximum $100 / 3B.",
         [{"at": 0.1, "event": "column headers"},
          {"at": 0.35, "event": "prices land"},
          {"at": 0.6, "event": "allowances land"}],
         claim="The table IS the content; building it cell by cell paces the numbers."),
    beat("B08", "money",
         "The API is priced separately: a dollar twenty-five per million input tokens, four twenty-five per million output. Or ten cents and twenty — if you let them train on your data. Twelve and a half times cheaper on input, twenty-one on output.",
         "M08_APIPricing",
         "An input/output bar pair; then a much smaller pair beside it, labeled 'with data sharing', each tagged with how many times cheaper it is.",
         [{"at": 0.15, "event": "standard bars"},
          {"at": 0.55, "event": "smaller sharing pair"},
          {"at": 0.8, "event": "12.5x and 21x cheaper land"}],
         claim="Bar lengths make the price gap visible; the multipliers name it."),
    beat("B24", "money",
         "Bear and Claude's read: that gap isn't a discount — it's a bid. More than ninety percent off, and in return Meta gets whatever you run through it: your usage, your appointments, your purchases, the tickets you pick.",
         "M24_TheDiscountIsABid",
         "The $1.25 price is struck through and drops to $0.10 with '92% off'; four cards — usage, appointments, purchases, tickets — slide from 'you' into Meta, which grows.",
         [{"at": 0.15, "event": "$1.25 chip"},
          {"at": 0.35, "event": "strike, drop to $0.10"},
          {"at": 0.55, "event": "four data cards appear"},
          {"at": 0.8, "event": "cards slide into Meta"}],
         claim="The price falls as the data cards move the other way: the discount IS the payment."),
    beat("B09", "money",
         "The business model — their core claim. Primary revenue: transaction fees. A small merchant-paid cut of every purchase Muse brokers, like an affiliate commission. The generous free tier is a bet those fees pay off. You never see a charge.",
         "M09_TransactionFees",
         "A shopper mark → Muse → merchant mark flow; a small coin siphons off to Meta.",
         [{"at": 0.15, "event": "purchase flow draws"},
          {"at": 0.5, "event": "coin siphons to Meta"}],
         claim="The siphoning coin is the business model in one motion."),
    beat("B10", "money",
         "Secondary streams: subscriptions, API sales — and two quieter ones. The ads angle: Meta says no ads inside Muse, but it funnels businesses toward Meta's ad machine, and your browsing shapes ads elsewhere. Plus training data — on by default.",
         "M10_SecondaryStreams",
         "Four small streams — subs, API, ads angle, training — converge into Meta.",
         [{"at": 0.15, "event": "four streams"},
          {"at": 0.55, "event": "streams converge"}],
         claim="Convergence shows many streams, one destination."),
    beat("B11", "money",
         "Their read of the goal: own the intent layer — shoppers one side, merchants the other, Meta in the middle. The skepticism: one analysis says only eleven of forty-seven payments are automatable. The fees may not carry it — and ads may come.",
         "M11_IntentLayer",
         "A funnel: 'I want…' in at the top, Meta in the middle, money out the bottom; then forty-seven coins appear and eleven light up.",
         [{"at": 0.1, "event": "funnel"},
          {"at": 0.5, "event": "forty-seven coins"},
          {"at": 0.8, "event": "eleven light up"}],
         claim="The funnel is the strategy; the eleven lit coins are the skepticism."),
    beat("B25", "money",
         "Now, a hundred million tokens as real work. Nik says he's eighteen percent through this week's free allowance. What's in his folder: thirteen film packages — two hundred twelve beats, about eight thousand words of narration, roughly an hour of film.",
         "M25_WhatTheAllowanceBought",
         "A 100M gauge fills to 18% in terracotta; four hero numbers land under it: 13 film packages, 212 beats, 8,149 words, about 62 minutes.",
         [{"at": 0.2, "event": "gauge fills to 18%"},
          {"at": 0.5, "event": "13 and 212 land"},
          {"at": 0.7, "event": "8,149 words and 62 min land"}],
         claim="The gauge fills as the folder's contents land: this is what the used share holds."),
    beat("B26", "money",
         "At that pace, the full hundred million is about seventy-two film packages a week — nearly six hours of film. Straight-line math from one week; a different week would look different.",
         "M26_AtThatPace",
         "The 100M bar fills with five and a half blocks, each one Nik's 18%; two hero numbers land: about 72 film packages, about 5.7 hours.",
         [{"at": 0.25, "event": "blocks fill the bar"},
          {"at": 0.55, "event": "72 lands"},
          {"at": 0.72, "event": "5.7 hours lands"}],
         claim="Repeating the 18% block until the bar is full IS the extrapolation."),
    beat("B27", "money",
         "If Muse tokens count like ordinary ones, those eight thousand words are about eleven thousand tokens — under a tenth of a percent of the eighteen million. Claude's read: the rest is the agent re-reading its own work. Tokens measure effort, not output.",
         "M27_TokensAreEffort",
         "A wide bar for 18M tokens with a hairline terracotta sliver at its left; a callout zooms the sliver into a block labeled 'the script', then the rest of the bar is named.",
         [{"at": 0.25, "event": "sliver flashes"},
          {"at": 0.45, "event": "callout zooms it up"},
          {"at": 0.7, "event": "the rest named"}],
         claim="The invisible sliver, zoomed, is how little of the spend is the visible work."),
    beat("B28", "money",
         "Price it the way Meta prices its API: a hundred million tokens is a hundred twenty-five to four hundred twenty-five dollars. Share your data, and it's ten to twenty. If the tokens compare — nobody can confirm that.",
         "M28_PriceItLikeTheAPI",
         "Two range bars: $125–$425 at the standard rate, $10–$20 if you let them train on your data; a caveat line below.",
         [{"at": 0.25, "event": "standard range bar"},
          {"at": 0.55, "event": "data-sharing range bar"},
          {"at": 0.85, "event": "caveat lands"}],
         claim="The tiny second bar is the price of letting them keep your data."),
    beat("B29", "money",
         "Their read: the free tier is a subsidy. Meta is buying a user base — and your data: what you do, what you book, what you buy. So be careful what goes through it. When it's cheap, ask what the discount buys.",
         "M29_TheSubsidyTell",
         "A balance: 'free tokens' on one pan, 'your data' on the other; the data pan sinks; a closing line reads 'cheap? ask what the discount buys'.",
         [{"at": 0.25, "event": "two pans"},
          {"at": 0.45, "event": "data items listed"},
          {"at": 0.65, "event": "beam tips toward the data"}],
         claim="The beam tipping toward the data pan is the subsidy argument."),
    # ── ACT IV — security concerns ────────────────────────────────────────
    beat("B12", "security concerns",
         "Concern one: Full Disk Access — the whole disk, not folder-level. Meta says it only touches files you ask about; Bear and Claude call that a behavioral promise, not a technical boundary. The machine can't tell the difference.",
         "M12_FullDisk",
         "A drive outline; a terracotta wash floods the entire thing, edge to edge.",
         [{"at": 0.15, "event": "drive outline"},
          {"at": 0.45, "event": "wash floods the whole disk"}],
         claim="Total coverage, shown totally — the wash is the claim."),
    beat("B13", "security concerns",
         "Concern two: a deny-list, not an allow-list. Nik can't grant one folder — he'd have to block every other disk by name, and any forgotten one is exposed. Fail-safe defaults, violated. Folder pickers could have worked — but Messages, Notes, and Mail need Full Disk Access.",
         "M13_DenyList",
         "Left: a list being crossed out item by endless item. Right: one folder with a ring around it.",
         [{"at": 0.1, "event": "deny-list crossing begins"},
          {"at": 0.45, "event": "crossing continues, endlessly"},
          {"at": 0.7, "event": "allow-list folder ringed"}],
         claim="The endless crossing-out versus the single ring IS fail-open versus fail-closed."),
    beat("B30", "security concerns",
         "Muse told Nik it would only touch one folder. That's a language model's promise — and language models hallucinate. Nik can't set a one-folder limit; it's the whole disk or nothing. A promise isn't a permission system.",
         "M30_PromiseNotPermission",
         "A disk with one folder inside; a thin ring labeled 'only this folder' is the promise; the ring stretches out across the whole disk while the disk border stays the only real setting.",
         [{"at": 0.15, "event": "disk and folder"},
          {"at": 0.35, "event": "the promise ring around the folder"},
          {"at": 0.6, "event": "ring stretches across the whole disk"},
          {"at": 0.85, "event": "'a promise, not a lock' lands"}],
         claim="The ring stretching past the folder is the promise failing with nothing to stop it."),
    beat("B14", "security concerns",
         "Concern three: known vulnerabilities. Malwarebytes reported a zero-day where a dictation redirect could steal an auth token — needs local code execution first. One researcher exported six point eight gigabytes of runtime data, SSH keys included. Plus early prompt-extraction reports.",
         "M14_Vulnerabilities",
         "Three warning triangles land in a row, each labeled: zero-day, data export, prompt extraction.",
         [{"at": 0.2, "event": "triangle one lands"},
          {"at": 0.45, "event": "triangle two lands"},
          {"at": 0.7, "event": "triangle three lands"}],
         claim="Three distinct findings, one visual language."),
    beat("B15", "security concerns",
         "Concern four: policy, not cryptography. Training on by default. The ad-systems separation is a policy claim — no independent audit. Every file you ask about is processed in Meta's cloud, and tokens pasted into chat live in the cloud past expiry.",
         "M15_PolicyNotCrypto",
         "A paper shield labeled 'policy' tears in half; a steel lock labeled 'crypto' holds firm.",
         [{"at": 0.15, "event": "paper shield"},
          {"at": 0.45, "event": "shield tears"},
          {"at": 0.7, "event": "steel lock holds"}],
         claim="The tearing paper is the argument."),
    beat("B16", "security concerns",
         "Concern five: prompt injection and approval fatigue. Any untrusted text — a webpage, an email, a PR, a code comment — can steer the agent, and the failure is adversarial, not random. Approvals only work if you read them; fatigue turns them into reflex.",
         "M16_InjectionFatigue",
         "A page with hidden terracotta text steers an agent dot off course; then approval cards get rubber-stamped faster and faster.",
         [{"at": 0.1, "event": "hidden text steers the dot"},
          {"at": 0.5, "event": "stamp speeds up"}],
         claim="Steering plus the accelerating stamp are both motions."),
    beat("B17", "security concerns",
         "Concern six: trust by design. The mascot, the persona — Bear and Claude call them trust shortcuts. A cute character reads as safe before it's earned it. And 'superintelligence' branding, they say, overpromises for what's really an errand agent.",
         "M17_TrustByDesign",
         "A cute mascot face; hearts rise from it — then a price tag drops onto it.",
         [{"at": 0.15, "event": "mascot face"},
          {"at": 0.4, "event": "hearts rise"},
          {"at": 0.7, "event": "price tag drops"}],
         claim="The price tag landing on the cute face is the critique."),
    beat("B18", "security concerns",
         "Concerns seven and eight. Business conflicts: affordability advice from the company selling the ads, self-graded attribution, advice that only ever points at Meta inventory. And platform dependence: lock-in, a shopper-optimized roadmap where developer features can vanish.",
         "M18_Conflicts",
         "Two panels: a scale tipping toward ads; a roadmap that shrinks.",
         [{"at": 0.15, "event": "scale tips"},
          {"at": 0.55, "event": "roadmap shrinks"}],
         claim="The tipping scale and the shrinking roadmap are the two critiques."),
    beat("B19", "security concerns",
         "Concern nine: the phone. Contacts, messages, health — the mobile permissions expose the most personal data of all. Nik won't use it there.",
         "M19_Phone",
         "A phone mark; permission toggles flip on, one after another — contacts, messages, health.",
         [{"at": 0.15, "event": "phone mark"},
          {"at": 0.4, "event": "toggles flip on"}],
         claim="The flipping toggles are the exposure."),
    # ── ACT V — how Bear resolved it ──────────────────────────────────────
    beat("B20", "how Bear resolved it",
         "How did Bear resolve it? First: nothing runs locally. The Mac app is gone — signed out, deleted, revoked, verified. Muse is web-only, through muse.ai, ideally in its own browser profile. Not on the phone.",
         "M20_MacAppGone",
         "A Mac app icon drops into a trash can; a browser window stays lit.",
         [{"at": 0.15, "event": "app icon drops into trash"},
          {"at": 0.55, "event": "browser window stays lit"}],
         claim="Removal in motion; what remains is the answer."),
    beat("B31", "how Bear resolved it",
         "That's the rule that matters most. Muse never runs on Nik's computer. It runs in the cloud, and it only sees what he puts there — a Google Drive folder, a sandbox repo. The wall is where the files live, not what Muse promises.",
         "M31_NothingRunsLocally",
         "A laptop labeled 'Nik's computer' is crossed out behind a wall; on the other side a cloud holds Muse, fed by two tiles — a Google Drive folder and a sandbox repo.",
         [{"at": 0.15, "event": "laptop and wall"},
          {"at": 0.35, "event": "laptop crossed out"},
          {"at": 0.55, "event": "cloud with Muse"},
          {"at": 0.75, "event": "Drive folder and repo feed the cloud"}],
         claim="The crossed-out laptop behind the wall IS the boundary: location, not language."),
    beat("B21", "how Bear resolved it",
         "Second: the film setup. Muse works only in its cloud VM, on public sandbox repos. GitHub is a dedicated bot account, sandbox repos only, no pasted tokens. PRs only, branch protection, Claude Code review, deterministic CI — rendering on a burner MacBook with no Muse.",
         "M21_Pipeline",
         "Five stations — VM, PR, review, merge, burner — and a dot travels the pipeline left to right.",
         [{"at": 0.1, "event": "five stations"},
          {"at": 0.35, "event": "dot travels the pipeline"}],
         claim="The traveling dot is the workflow."),
    beat("B22", "how Bear resolved it",
         "Third: the general rules. Assume breach. Bound the blast radius. Enforce caps outside the agent — a card limit, not an instruction. Irreversible actions get a human. And protect the short list — email, money, credentials, public voice — with real walls, not policies.",
         "M22_GeneralRules",
         "A wall; behind it four marks — email, money, credentials, voice.",
         [{"at": 0.15, "event": "the wall"},
          {"at": 0.5, "event": "four marks behind it"}],
         claim="The wall with the valuables behind it is 'bound the blast radius'."),
    # ── ACT VI — open questions ───────────────────────────────────────────
    beat("B23", "open questions",
         "Six questions stay open. VM disk and compute limits? GitHub connector OAuth scopes? What does a 'Muse token' map to? Will confidential mode ship — with what guarantees? How long does the free tier stay generous? And do ads come to Muse?",
         "M23_OpenQuestions",
         "Six question marks land in a three-by-two grid.",
         [{"at": 0.15, "event": "first row lands"},
          {"at": 0.5, "event": "second row lands"}],
         claim="Open questions, visually open."),
]

OPEN = [
    remotion(
        "BIDEA", "the question",
        "Hallo. This is Liam, in for Bear. You've heard what Meta tells you about Muse. Now here's what Bear and Claude think — their read on what it does, what it costs, and where the risks are.",
        "BrutalistHesitantWriter",
        {"text": "What is Muse —\nwhat Meta tells you?",
         "triggerWords": "what Meta tells you",
         "replacementWords": "what Bear and Claude think",
         "fontSize": 70, "charMs": 22, "hesitateBetween": 6,
         "hesitateWithin": 1, "mistakeRate": 2, "jitter": 20,
         "seed": SLUG, "banner": ""},
        [{"at": 0.0, "event": "types 'What is Muse —'"},
         {"at": 0.5, "event": "backspaces 'what Meta tells you' → 'what Bear and Claude think' on the spoken correction"}],
        lead_silence_s=0.8,
        motion_claim="The writer types the launch-hype framing and corrects it to the opinion framing: Bear and Claude's read.",
        qc={"sparse_by_design": True,
            "sparse_reason": "Hesitant-writer bookend: the correction is the motion."},
    ),
    remotion(
        "BDEFS", "terms",
        "Six terms. Agent: a program that works for you on its own. Connector: a plug-in to an outside service. Token: a word-sized chunk of text an AI reads or writes. Allow-list: only named things get access. Prompt injection: hidden instructions steer it. Intent layer: where you say what you want.",
        "ClaudeDefinitions",
        {"title": "Terms In This Lecture",
         "terms": [
             {"term": "agent", "meaning": "a program that works for you on its own"},
             {"term": "connector", "meaning": "a plug-in to an outside service"},
             {"term": "token", "meaning": "a word-sized chunk of text"},
             {"term": "allow-list", "meaning": "only named things get access"},
             {"term": "prompt injection", "meaning": "hidden instructions steer it"},
             {"term": "intent layer", "meaning": "where you say what you want"},
         ],
         "folderLabel": "@NikBearBrown"},
        [{"at": 0.1, "event": "'agent' lands"},
         {"at": 0.27, "event": "'connector' lands"},
         {"at": 0.43, "event": "'token' lands"},
         {"at": 0.58, "event": "'allow-list' lands"},
         {"at": 0.72, "event": "'prompt injection' lands"},
         {"at": 0.86, "event": "'intent layer' lands"}],
        gate="CARD",
        qc={"sparse_by_design": True,
            "sparse_reason": "TERMS card: six prerequisites, one line each."},
    ),
]

B = OPEN + B + [
    remotion(
        "BVDT", "recap",
        "Let's recap with Claude. "
        "Muse is Meta's consumer agent — it acts on errands, with endurance more than intelligence. "
        "It costs nothing to start, but the cheapest tokens are paid for with your data; twenty or a hundred dollars a month buys volume, not features. "
        "Meta's bet is transaction fees on every purchase it brokers — plus the intent layer itself. "
        "The critique: full disk access, a deny-list, real vulnerabilities, and policy where crypto should be. "
        "Bear's answer: nothing runs locally — web and cloud only, files in Drive and sandbox repos, reviewed PRs. "
        "Open questions: token limits, scopes, confidential mode — and whether the free ride lasts.",
        "ClaudeVerdictArtifact",
        {"artifactTitle": "Claude on Muse",
         "artifactHeading": "Recap",
         "brandLabel": "@NikBearBrown",
         "artifactLines": [
             "Muse is Meta's consumer agent — acts on errands, endurance over intelligence.",
             "Free to start; the cheapest tokens cost your data.",
             "Meta's bet: transaction fees on every purchase — plus the intent layer.",
             "The critique: full disk access, a deny-list, real vulns, policy not crypto.",
             "Bear's answer: nothing local — cloud only, Drive and sandbox repos.",
             "Open: token limits, scopes, confidential mode, whether the free ride lasts.",
         ]},
        [{"at": 0.1, "event": "line 1 lands"},
         {"at": 0.28, "event": "line 2 lands"},
         {"at": 0.46, "event": "line 3 lands"},
         {"at": 0.62, "event": "line 4 lands"},
         {"at": 0.78, "event": "line 5 lands"},
         {"at": 0.9, "event": "line 6 lands"}],
    ),
    remotion(
        "BHTF", "your turn",
        "Your turn. List every AI app on your computer with disk access. For each one, write down whether it uses an allow-list or a deny-list. Then check two things yourself. Did you find every app? And can you say which list model each one uses?",
        "ClaudeComposerAsk",
        {"greeting": "Your turn.", "topic": "MUSE · YOUR TURN",
         "segment": "Audit Your AI Apps", "command": "Open System Settings, Privacy & Security, Full Disk Access — and list every AI app you see",
         "runningText": "listing your AI apps…",
         "output": ["Check: you found every AI app with disk access.",
                    "Check: you can say allow-list or deny-list for each."],
         "folderLabel": "@NikBearBrown", "modelLabel": "Muse Spark", "effortLabel": "Low"},
        [{"at": 0.0, "event": "Composer opens — 'Your turn.'"},
         {"at": 0.1, "event": "the prompt types in full"},
         {"at": 0.8, "event": "two check lines land"}],
    ),
    {
        "beat_id": "BOUT", "act": "outro", "lane": "bookend", "proof_gate": "SHOW",
        "narration_text": f"{TITLE}. At Nik Bear Brown.",
        "estimated_duration_s": 4.0, "voice": "am_onyx", "engine": "kokoro",
        "shot": {
            "type": "REMOTION", "source": "own",
            "show": [{"at": 0.0, "event": "title restates; handle; mascot"}],
            "remotion": {
                "pattern": "ClaudeTitleOutro",
                "props": {"title": TITLE, "slug": SLUG,
                          "handle": "@NikBearBrown", "subline": ""},
            },
        },
        "kind": "outro_voice", "tail_silence_s": 1.0,
    },
]

sheet = {
    "metadata": {
        "slug": SLUG, "title": TITLE, "topic": "MUSE · CLAUDE'S TAKE",
        "skill": "lecture", "style_preset": "lecture",
        "channel": "claude-liam", "persona": "Liam (in for Bear)",
        "voice": "am_onyx", "voice_kokoro": "am_onyx", "engine": "kokoro",
        "clock": "narration", "palette": "claude", "register": "Teardown",
        "fps": 24, "aspect_ratio": "16:9", "width": 3840, "height": 2160,
        "caption_policy": "none", "greeting_language": "German/Dutch (Hallo)",
        "audience": "anyone who heard Meta's Muse pitch and wants Bear and Claude's read",
        "source_doc": "Bear's pasted doc (2026-10-03): 'Meta Muse: What It Does, Security Concerns, and Business Model'",
        "playlist": "Muse", "chapter_number": 0,
        "tags": ["Muse", "Meta", "AI agents", "security", "business model", "Nik Bear Brown"],
    },
    "beats": B,
}
(HERE / "beat_sheet.json").write_text(json.dumps(sheet, indent=2, ensure_ascii=False) + "\n")
print(len(B), "beats; est", round(sum(b["estimated_duration_s"] for b in B)), "s")
